
GO

/****** Object:  Index [DIndex]    Script Date: 7/16/2014 4:00:57 PM ******/
CREATE NONCLUSTERED INDEX [DIndex] ON [dbo].[Attendances]
(
	[Year] ASC,
	[Month] ASC,
	[Day] ASC,
	[Hour] ASC,
	[Minute] ASC,
	[Second] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_LocationId]    Script Date: 7/16/2014 12:54:45 PM ******/
CREATE NONCLUSTERED INDEX [IX_LocationId] ON [dbo].[Attendances]
(
	[LocationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_CardAccessLevelId]    Script Date: 7/16/2014 12:55:19 PM ******/
CREATE NONCLUSTERED INDEX [IX_CardAccessLevelId] ON [dbo].[Cards]
(
	[CardAccessLevelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CardCategoryId] ON [dbo].[Cards]
(
	[CardCategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_EmployeeId]    Script Date: 7/16/2014 12:57:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_EmployeeId] ON [dbo].[EmployeeOnSites]
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_LocationId] ON [dbo].[EmployeeOnSites]
(
	[LocationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IX_SyncSessionLogId] ON [dbo].[SyncLogEntries]
(
	[SyncSessionLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [IX_SyncSessionLogId]    Script Date: 7/16/2014 12:58:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_SyncSessionLogId] ON [dbo].[SyncMachineLogs]
(
	[SyncSessionLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



/****** Object:  Index [IX_Employee_Id]    Script Date: 7/16/2014 12:59:04 PM ******/
CREATE NONCLUSTERED INDEX [IX_Employee_Id] ON [dbo].[TeamAllocations]
(
	[Employee_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_Team_TeamId]    Script Date: 7/16/2014 12:59:20 PM ******/
CREATE NONCLUSTERED INDEX [IX_Team_TeamId] ON [dbo].[TeamAllocations]
(
	[Team_TeamId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_CreatedBy_Id]    Script Date: 7/16/2014 12:59:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_CreatedBy_Id] ON [dbo].[UserTeams]
(
	[CreatedBy_EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [IX_CardAccessLevelId]    Script Date: 7/16/2014 1:00:16 PM ******/
CREATE NONCLUSTERED INDEX [IX_CardAccessLevelId] ON [dbo].[VisitInformations]
(
	[CardAccessLevelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [IX_EntityId]    Script Date: 7/16/2014 1:00:30 PM ******/
CREATE NONCLUSTERED INDEX [IX_EntityId] ON [dbo].[VisitInformations]
(
	[EntityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/****** Object:  Index [IX_LocationId]    Script Date: 7/16/2014 1:00:51 PM ******/
CREATE NONCLUSTERED INDEX [IX_LocationId] ON [dbo].[VisitorAttendances]
(
	[LocationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_EmployeeId]    Script Date: 7/16/2014 1:01:21 PM ******/
CREATE NONCLUSTERED INDEX [IX_EmployeeId] ON [dbo].[VisitorPassAllocations]
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

